kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: edge-automl-flowers
  namespace: edge-automl-flowers
spec:
  to:
    kind: Service
    name: edge-automl-flowers
    weight: 100
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None